Repository threefoldtech/0-templates, pull requests merged in 2018-10, with the labels that each got.

#140 Extend vm templates to allow passing kernelArgs
  templates/dm_vm/README.md
  templates/dm_vm/dm_vm.py
  templates/dm_vm/schema.capnp
  templates/s3/s3.py
  templates/vm/README.md
  templates/vm/schema.capnp
  templates/vm/vm.py
Labels: state_verification

#125 WIP: Implement etcd, traefik and coredns templates
  templates/coredns/README.md
  templates/coredns/coredns.py
  templates/coredns/schema.capnp
  templates/etcd/README.md
  templates/etcd/etcd.py
  templates/etcd/schema.capnp
  templates/minio/README.md
  templates/minio/minio.py
  templates/traefik/README.md
  templates/traefik/schema.capnp
  templates/traefik/traefik.py
  templates/zerodb/README.md
  templates/zerodb/schema.capnp
  templates/zerodb/zerodb.py
  templates/zerodb/zerodb_test.py
Labels: state_verification

#147 use GUID instead of random char to generate name
  templates/node/node.py
  templates/s3/s3.py
Labels: state_verification

#135 zrobot config
  templates/zrobot_config/zrobot_config.py
Labels: state_verification

#157 Allow configuring the master tlog in minio
  templates/minio/README.md
  templates/minio/minio.py
  templates/minio/schema.capnp
Labels: state_inprogress, state_verification

#162 selfhealing for network
  templates/network/network.py
  templates/network/schema.capnp
Labels: state_inprogress, state_verification

#161 Implement s3 manager to manage passive and active s3
  templates/s3/s3.py
  templates/s3/s3_test.py
  templates/s3/schema.capnp
  templates/s3_manager/s3_manager.py
  templates/s3_manager/schema.capnp
Labels: state_inprogress, state_verification

#165 Development network deconfigure
  templates/network/network.py
Labels: in progress, state_inprogress, state_verification

#170 use 0-robot api to get other robot connections
  templates/dm_gateway/dm_gateway.py
  templates/dm_vm/dm_vm.py
  templates/dm_vm/dm_vm_test.py
  templates/minio/README.md
  templates/s3/s3.py
  templates/s3/s3_test.py
  templates/zerotier_client/zerotier_client.py
Labels: in progress, state_inprogress, state_verification

#175 add node_ip template
  templates/node_ip/README.md
  templates/node_ip/node_ip.py
  templates/node_ip/schema.capnp
Labels: in progress, state_inprogress, state_verification

#181 Refactor container template
  templates/container/container.py
  templates/container/container_test.py
Labels: in progress, state_inprogress, state_verification

#182 Refactor s3_redundant
  templates/s3/README.md
  templates/s3/s3.py
  templates/s3/schema.capnp
  templates/s3_redundant/s3_redundant.py
Labels: in progress, state_inprogress, state_verification

#176 Zdb testcases
  tests/controller/controller.py
  tests/controller/templates_manager/local_temp/zerodb.py
  tests/testcases/a_basics/zdb_testcases.py
  tests/testcases/base_test.py
Labels: in progress, state_inprogress, state_verification

#185 add port_manager template
  templates/minio/README.md
  templates/minio/minio.py
  templates/minio/schema.capnp
  templates/node/node.py
  templates/node_port_manager/README.md
  templates/node_port_manager/node_port_manager.py
  templates/node_port_manager/node_port_manager_test.py
  templates/node_port_manager/schema.capnp
  templates/vm/vm.py
  templates/zerodb/README.md
  templates/zerodb/schema.capnp
  templates/zerodb/zerodb.py
  templates/zrobot/zrobot.py
Labels: in progress, state_inprogress, state_verification

#188 Minio Log processing
  templates/minio/minio.py
  templates/minio/minio_test.py
  templates/s3_redundant/s3_redundant.py
Labels: in progress, state_inprogress, state_verification

#189 S3 selfhealing zdb
  templates/s3/s3.py
  templates/s3_redundant/s3_redundant.py
Labels: in progress, state_inprogress, state_verification
